
<?php


$filmes = [
    [
        "nome" => "Thunderbolts*",
        "ano" => 2025,
        "genero" => "Ação",
        "genero2" => "Ficção Cientifica",
        "elencoPrincipal" => "Florence Pugh, Lewis Pullman, Sebastian Stan",
        "direcao" => "Jake Schreier",
        "produtora" => "Marvel",
        "classificacao" => "14",
        "duracao" => "2h6m",
        "id" => "thunderbolts",
    ],
    [
        "nome" => "A Fuga das Galinhas",
        "ano" => 2000,
        "genero" => "Animação",
        "genero2" => "Comédia",
        "elencoPrincipal" => "Mel Gibson, Julia Sawalha, Imelda Staunton",
        "direcao" => "Peter Lord, Nick Park",
        "produtora" => "Aardman Animations, DreamWorks Animation",
        "classificacao" => "Livre",
        "duracao" => "1h24m",
        "id" => "a-fuga-das-galinhas"
    ],
    [
        "nome" => "Ainda Estou Aqui",
        "ano" => 2024,
        "genero" => "Drama",
        "genero2" => "Suspense",
        "elencoPrincipal" => "Fernanda Torres, Fernanda Montenegro, Selton Mello",
        "direcao" => "Walter Salles",
        "produtora" => "Produção Nacional",
        "classificacao" => "14",
        "duracao" => "2h15m",
        "id" => "ainda-estou-aqui"
    ],
    [
        "nome" => "Cidade de Deus",
        "ano" => 2002,
        "genero" => "Policial",
        "genero2" => "Drama",
        "elencoPrincipal" => "Alexandre Rodrigues, Leandro Firmino, Seu Jorge",
        "direcao" => "Fernando Meirelles, Kátia Lund",
        "produtora" => "O2 Filmes, Videofilmes",
        "classificacao" => "16",
        "duracao" => "2h15m",
        "id" => "cidade-de-deus"
    ],
    [
        "nome" => "Conclave",
        "ano" => 2024,
        "genero" => "Suspense",
        "genero2" => "Mistério",
        "elencoPrincipal" => "Ralph Fiennes, Stanley Tucci, John Lithgow",
        "direcao" => "Edward Berger",
        "produtora" => "Focus Features, Black Bear UK",
        "classificacao" => "14",
        "duracao" => "1h50m",
        "id" => "conclave"
    ],
    [
        "nome" => "Coraline",
        "ano" => 2009,
        "genero" => "Animação",
        "genero2" => "Fantasia",
        "elencoPrincipal" => "Dakota Fanning, Teri Hatcher, Keith David",
        "direcao" => "Henry Selick",
        "produtora" => "Laika, Focus Features",
        "classificacao" => "10",
        "duracao" => "1h40m",
        "id" => "coraline"
    ],
    [
        "nome" => "Deu a Louca na Chapeuzinho",
        "ano" => 2004,
        "genero" => "Animação",
        "genero2" => "Comédia",
        "elencoPrincipal" => "Anne Hathaway, Glenn Close, Patrick Warburton",
        "direcao" => "Cory Edwards, Todd Edwards, Tony Leech",
        "produtora" => "Kanbar Entertainment",
        "classificacao" => "Livre",
        "duracao" => "1h20m",
        "id" => "deu-a-louca-na-chapeuzinho"
    ],
    [
        "nome" => "Estômago",
        "ano" => 2007,
        "genero" => "Drama",
        "genero2" => "Comédia",
        "elencoPrincipal" => "João Miguel, Fabiula Nascimento, Babu Santana",
        "direcao" => "Marcos Jorge",
        "produtora" => "Zencrane Filmes",
        "classificacao" => "16",
        "duracao" => "1h52m",
        "id" => "estomago"
    ],
    [
        "nome" => "Internet: O Filme",
        "ano" => 2017,
        "genero" => "Comédia",
        "genero2" => "Ficção",
        "elencoPrincipal" => "Rafinha Bastos, Felipe Castanhari, Kéfera Buchmann",
        "direcao" => "Fillipo Capuzzi Lapietra",
        "produtora" => "Produção Nacional",
        "classificacao" => "14",
        "duracao" => "1h30m",
        "id" => "internet-o-filme"
    ],
    [
        "nome" => "Jimmy Neutron: O Menino Gênio",
        "ano" => 2001,
        "genero" => "Animação",
        "genero2" => "Ficção Científica",
        "elencoPrincipal" => "Debi Derryberry, Rob Paulsen, Megan Cavanagh",
        "direcao" => "John A. Davis",
        "produtora" => "Nickelodeon Movies, Paramount Pictures",
        "classificacao" => "Livre",
        "duracao" => "1h30m",
        "id" => "jimmy-neutron-o-menino-genio"
    ],
    [
        "nome" => "Um Filme Minecraft",
        "ano" => 2025,
        "genero" => "Aventura",
        "genero2" => "Comédia",
        "elencoPrincipal" => "Jason Momoa, Jack Black, Danielle Brooks",
        "direcao" => "Jared Hess",
        "produtora" => "Warner Bros.",
        "classificacao" => "10",
        "duracao" => "1h41m",
        "id" => "um-filme-minecraft"
    ],
    [
        "nome" => "Missão Impossível: O Acerto Final",
        "ano" => 2025,
        "genero" => "Ação",
        "genero2" => "Suspense",
        "elencoPrincipal" => "Tom Cruise, Hayley Atwell, Ving Rhames",
        "direcao" => "Christopher McQuarrie",
        "produtora" => "Paramount Pictures",
        "classificacao" => "14",
        "duracao" => "2h30m",
        "id" => "missao-impossivel-o-acerto-final"
    ],
    [
        "nome" => "My Little Pony: O Filme",
        "ano" => 2017,
        "genero" => "Animação",
        "genero2" => "Fantasia",
        "elencoPrincipal" => "Tara Strong, Emily Blunt, Zoe Saldana",
        "direcao" => "Jayson Thiessen",
        "produtora" => "Hasbro Studios, Lionsgate",
        "classificacao" => "Livre",
        "duracao" => "1h39m",
        "id" => "my-little-pony-o-filme"
    ],
    [
        "nome" => "Os Carrinhos",
        "ano" => 2006,
        "genero" => "Animação",
        "genero2" => "Infantil",
        "elencoPrincipal" => "Vozes desconhecidas",
        "direcao" => "Produção Nacional",
        "produtora" => "Video Brinquedo",
        "classificacao" => "Livre",
        "duracao" => "1h10m",
        "id" => "os-carrinhos"
    ],
    [
        "nome" => "Premonição 6",
        "ano" => 2025,
        "genero" => "Terror",
        "genero2" => "Suspense",
        "elencoPrincipal" => "Elenco a ser anunciado",
        "direcao" => "Zach Lipovsky, Adam B. Stein",
        "produtora" => "New Line Cinema",
        "classificacao" => "16",
        "duracao" => "1h40m",
        "id" => "premonicao-6"
    ],
    [
        "nome" => "O Segredo dos Guardiões",
        "ano" => 2012,
        "genero" => "Animação",
        "genero2" => "Aventura",
        "elencoPrincipal" => "Chris Pine, Alec Baldwin, Hugh Jackman",
        "direcao" => "Peter Ramsey",
        "produtora" => "DreamWorks Animation",
        "classificacao" => "Livre",
        "duracao" => "1h37m",
        "id" => "o-segredo-dos-guardioes"
    ],
    [
        "nome" => "Lilo & Stitch (Live Action)",
        "ano" => 2025,
        "genero" => "Aventura",
        "genero2" => "Comédia",
        "elencoPrincipal" => "Elenco a ser anunciado",
        "direcao" => "Dean Fleischer Camp",
        "produtora" => "Walt Disney Pictures",
        "classificacao" => "Livre",
        "duracao" => "1h45m",
        "id" => "lilo-e-stitch-live-action"
    ],
    [
        "nome" => "Tropa de Elite",
        "ano" => 2007,
        "genero" => "Ação",
        "genero2" => "Drama",
        "elencoPrincipal" => "Wagner Moura, André Ramiro, Caio Junqueira",
        "direcao" => "José Padilha",
        "produtora" => "Zazen Produções",
        "classificacao" => "16",
        "duracao" => "1h55m",
        "id" => "tropa-de-elite"
    ],
    [
        "nome" => "Tropa de Elite 2",
        "ano" => 2010,
        "genero" => "Ação",
        "genero2" => "Drama",
        "elencoPrincipal" => "Wagner Moura, Irandhir Santos, André Ramiro",
        "direcao" => "José Padilha",
        "produtora" => "Zazen Produções",
        "classificacao" => "16",
        "duracao" => "1h55m",
        "id" => "tropa-de-elite-2"
    ],
    [
        "nome" => "O Brutalista",
        "ano" => 2024,
        "genero" => "Drama",
        "genero2" => "Histórico",
        "elencoPrincipal" => "Adrien Brody, Felicity Jones",
        "diretor" => "Brady Corbet",
        "produtora" => "A24",
        "classificacao" => "16",
        "duracao" => "2h15m",
        "id" => "o-brutalista"
    ],
    [
        "nome" => "A Substância",
        "ano" => 2024,
        "genero" => "Terror",
        "genero2" => "Ficção Científica",
        "elencoPrincipal" => "Demi Moore",
        "direcao" => "Coralie Fargeat",
        "produtora" => "Universal Pictures",
        "classificacao" => "18",
        "duracao" => "1h50m",
        "id" => "a-substancia"
    ],
    [
        "nome" => "Duna: Parte 2",
        "ano" => 2024,
        "genero" => "Ficção Científica",
        "genero2" => "Aventura",
        "elencoPrincipal" => "Timothée Chalamet, Zendaya",
        "direcao" => "Denis Villeneuve",
        "produtora" => "Warner Bros.",
        "classificacao" => "14",
        "duracao" => "2h45m",
        "id" => "duna-parte-2"
    ],
];
$series = [
    [
        "nome" => "Loki",
        "ano_de_inicio" => 2021,
        "ano_de_encerramento" => 2023,
        "elencoPrincipal" => "Tom Hiddleston, Sophia Di Martino, Owen Wilson",
        "direcao" => "Kate Herron (1ª temporada), Justin Benson e Aaron Moorhead (2ª temporada)",
        "produtora" => "Marvel Studios",
        "classificacao" => 10,
        "genero" => "Ficção Científica",
        "genero2" => "Aventura",
        "numero_de_temporadas" => 2,
        "id" => "loki"
    ],
      [
        "nome" => "Anne with an E",
        "ano_de_inicio" => 2017,
        "ano_de_encerramento" => 2019,
        "elencoPrincipal" => "Amybeth McNulty, Geraldine James, R.H. Thomson",
        "direcao" => "Moira Walley-Beckett",
        "produtora" => "CBC, Netflix",
        "classificacao" => 12,
        "genero" => "Drama",
        "genero2" => "Coming-of-Age",
        "numero_de_temporadas" => 3,
        "id" => "anne-with-an-e"
    ],
    [
        "nome" => "Stranger Things",
        "ano_de_inicio" => 2016,
        "ano_de_encerramento" => null,
        "elencoPrincipal" => "Winona Ryder, David Harbour, Millie Bobby Brown",
        "direcao" => "Irmãos Duffer",
        "produtora" => "Netflix",
        "classificacao" => 14,
        "genero" => "Ficção Científica",
        "genero2" => "Terror",
        "numero_de_temporadas" => 4,
        "id" => "stranger-things"
    ],
    [
        "nome" => "The Last of Us",
        "ano_de_inicio" => 2023,
        "ano_de_encerramento" => null,
        "elencoPrincipal" => "Pedro Pascal, Bella Ramsey",
        "direcao" => "Craig Mazin, Neil Druckmann",
        "produtora" => "HBO",
        "classificacao" => 16,
        "genero" => "Drama",
        "genero2" => "Pós-apocalíptico",
        "numero_de_temporadas" => 2,
        "id" => "the-last-of-us"
    ],
    [
        "nome" => "Cavaleiro da Lua",
        "ano_de_inicio" => 2022,
        "ano_de_encerramento" => 2022,
        "elencoPrincipal" => "Oscar Isaac, Ethan Hawke, May Calamawy",
        "direcao" => "Mohamed Diab, Justin Benson, Aaron Moorhead",
        "produtora" => "Marvel Studios",
        "classificacao" => 14,
        "genero" => "Ação",
        "genero2" => "Aventura",
        "numero_de_temporadas" => 1,
        "id" => "cavaleiro-da-lua"
    ],
    [
        "nome" => "Doctor Who",
        "ano_de_inicio" => 2005,
        "ano_de_encerramento" => null,
        "elencoPrincipal" => "Vários atores ao longo das temporadas",
        "direcao" => "Vários diretores",
        "produtora" => "BBC",
        "classificacao" => 12,
        "genero" => "Ficção Científica",
        "genero2" => "Aventura",
        "numero_de_temporadas" => 15,
        "id" => "doctor-who"
    ],
    [
        "nome" => "Link Click",
        "ano_de_inicio" => 2021,
        "ano_de_encerramento" => null,
        "elencoPrincipal" => "Su Shangqing, Yang Tianxiang",
        "direcao" => "Li Haoling",
        "produtora" => "Studio LAN",
        "classificacao" => 14,
        "genero" => "Drama",
        "genero2" => "Fantasia",
        "numero_de_temporadas" => 2,
        "id" => "link-click"
    ],
    [
        "nome" => "Good Omens",
        "ano_de_inicio" => 2019,
        "ano_de_encerramento" => null,
        "elencoPrincipal" => "Michael Sheen, David Tennant",
        "direcao" => "Douglas Mackinnon",
        "produtora" => "Amazon Studios, BBC Studios",
        "classificacao" => 16,
        "genero" => "Fantasia",
        "genero2" => "Comédia",
        "numero_de_temporadas" => 2,
        "id" => "good-omens"
    ],
    [
        "nome" => "Supernatural",
        "ano_de_inicio" => 2005,
        "ano_de_encerramento" => 2020,
        "elencoPrincipal" => "Jared Padalecki, Jensen Ackles",
        "direcao" => "Vários diretores",
        "produtora" => "Warner Bros. Television",
        "classificacao" => 16,
        "genero" => "Terror",
        "genero2" => "Fantasia",
        "numero_de_temporadas" => 15,
        "id" => "supernatural"
    ],
    [
        "nome" => "Sherlock",
        "ano_de_inicio" => 2010,
        "ano_de_encerramento" => 2017,
        "elencoPrincipal" => "Benedict Cumberbatch, Martin Freeman",
        "direcao" => "Paul McGuigan, Euros Lyn, Toby Haynes",
        "produtora" => "BBC",
        "classificacao" => 14,
        "genero" => "Mistério",
        "genero2" => "Drama",
        "numero_de_temporadas" => 4,
        "id" => "sherlock"
    ],
    [
        "nome" => "Love, Death & Robots",
        "ano_de_inicio" => 2019,
        "ano_de_encerramento" => null,
        "elencoPrincipal" => "Vários atores (antologia)",
        "direcao" => "Vários diretores",
        "produtora" => "Netflix",
        "classificacao" => 18,
        "genero" => "Animação",
        "genero2" => "Ficção Científica",
        "numero_de_temporadas" => 4,
        "id" => "love-death-and-robots"
    ],
    [
        "nome" => "Breaking Bad",
        "ano_de_inicio" => 2008,
        "ano_de_encerramento" => 2013,
        "elencoPrincipal" => "Bryan Cranston, Aaron Paul",
        "direcao" => "Vince Gilligan",
        "produtora" => "AMC",
        "classificacao" => 18,
        "genero" => "Crime",
        "genero2" => "Drama",
        "numero_de_temporadas" => 5,
        "id" => "breaking-bad"
    ],
    [
        "nome" => "Better Call Saul",
        "ano_de_inicio" => 2015,
        "ano_de_encerramento" => 2022,
        "elencoPrincipal" => "Bob Odenkirk, Jonathan Banks",
        "direcao" => "Vince Gilligan, Peter Gould",
        "produtora" => "AMC",
        "classificacao" => 16,
        "genero" => "Crime",
        "genero2" => "Drama",
        "numero_de_temporadas" => 6,
        "id" => "better-call-saul"
    ],
    [
        "nome" => "Invencível",
        "ano_de_inicio" => 2021,
        "ano_de_encerramento" => null,
        "elencoPrincipal" => "Steven Yeun, J.K. Simmons, Sandra Oh",
        "direcao" => "Jeff Allen",
        "produtora" => "Amazon Studios",
        "classificacao" => 18,
        "genero" => "Animação",
        "genero2" => "Super-herói",
        "numero_de_temporadas" => 2,
        "id" => "invencivel"
    ],
    [
        "nome" => "Dark",
        "ano_de_inicio" => 2017,
        "ano_de_encerramento" => 2020,
        "elencoPrincipal" => "Louis Hofmann, Karoline Eichhorn",
        "direcao" => "Baran bo Odar",
        "produtora" => "Netflix",
        "classificacao" => 16,
        "genero" => "Ficção Científica",
        "genero2" => "Mistério",
        "numero_de_temporadas" => 3,
        "id" => "dark"
    ]
];

$destaques = ["thunderbolts", "my-little-pony-o-filme", "loki"];
$ganhadoresOscar = ["ainda-estou-aqui", "brutalista", "conclave", "flow", "duna-parte-2", "a-substancia"];
$generos = [
    "Ação",
    "Aventura",
    "Animação",
    "Comédia",
    "Drama",
    "Ficção Científica",
    "Terror",
];